# Generated by Django 6.0 on 2025-12-17 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usernotificationsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizenprofile',
            old_name='occupation',
            new_name='profession',
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='citizenprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
