# Generated by Django 6.0 on 2025-12-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_occupation_citizenprofile_profession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenprofile',
            name='badge',
            field=models.CharField(default='New Citizen', max_length=50),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
